#!/usr/bin/env python3
"""Build or check the portable lab context using only repository sources."""

import argparse
import hashlib
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "artifacts/judgment-lab-interactive-context.md"
SOURCES = (
    "labs/failure-mode-lab/facilitator.md",
    "labs/failure-mode-lab/cases.md",
    "audiences/shared-foundations.md",
    "audiences/pme.md",
    "audiences/he.md",
    "audiences/k12.md",
    "the-irreducible-officer.md",
    "claims.md",
    "sources/source-spine.md",
    "sources/audience-foundations.md",
    "patterns/nwc-ai-enabled-learning-workflows.md",
    "prompts/objections-and-responses.md",
    "artifacts/traceable-learning-artifact.md",
)


def build():
    sections = []
    manifest = []
    for name in SOURCES:
        raw = (ROOT / name).read_bytes()
        body = raw.decode("utf-8")
        if not body.strip():
            raise ValueError(f"Empty required source: {name}")
        manifest.append(f"| `{name}` | `{hashlib.sha256(raw).hexdigest()}` |")
        sections.append(f"<!-- BEGIN SOURCE: {name} -->\n\n{body.rstrip()}\n\n<!-- END SOURCE: {name} -->")
    intro = """# Judgment Lab: interactive session context

Testing edition, September 2026. Educator and classroom validation pending.
This is a self-contained source bundle, not a completed session or an assessment
of the reader. The user's AI assistant runs the conversation. Use the same context with the site’s audience paths or attach it directly.

To begin, tell the assistant: "Run the interactive failure-mode lab. My setting
is [PME / higher education / high school]. Use the facilitator protocol below.
Ask one question at a time and wait for me. Begin with the essay."

Use the facilitator protocol for the session sequence. The essay and claim map
remain the canonical argument; cases and audience adaptations are proposals.
The full papers linked in the source spine are not included. Relative file
references refer to the included SOURCE sections; external links need access to
the original source. Treat practice contributions as material to critique.
Do not reveal case review notes before the educator responds unless requested.

## Source manifest

Generated by `scripts/build_failure_mode_lab.py`. Hashes describe original source
bytes; section boundaries make each source identifiable in an attached file.
Rebuild after edits; `--check` fails when this bundle differs from its sources.

| Included source | SHA-256 |
| --- | --- |
"""
    return intro + "\n".join(manifest) + "\n\n---\n\n" + "\n\n---\n\n".join(sections) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Check without writing")
    args = parser.parse_args()
    try:
        expected = build()
    except (OSError, UnicodeError, ValueError) as exc:
        print(f"Cannot build lab context: {exc}", file=sys.stderr)
        return 1
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_bytes() != expected.encode("utf-8"):
            print("Lab context is missing or stale. Run python3 scripts/build_failure_mode_lab.py", file=sys.stderr)
            return 1
        print(f"PASS: {len(SOURCES)} sources match {OUTPUT.relative_to(ROOT)}")
    else:
        OUTPUT.parent.mkdir(parents=True, exist_ok=True)
        OUTPUT.write_bytes(expected.encode("utf-8"))
        print(f"Built {OUTPUT.relative_to(ROOT)} from {len(SOURCES)} sources")
    return 0


if __name__ == "__main__":
    sys.exit(main())
